services:
  app:
    container_name: fasten-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ES_HOST: http://elasticsearch:9200
      ES_USER: elastic
      ES_PASSWORD: changeme
      ES_INDEX_NAME: fasten-index
      EMBEDDING_MODEL_NAME: all-MiniLM-L6-v2
      LLM_HOST: http://llama:9090

    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/app/data
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: always
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload



  elasticsearch:
    container_name: fasten-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
    ports:
      - "9200:9200"
    mem_limit: 512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cat/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  llama:
    container_name: fasten-llama
    image: ghcr.io/ggerganov/llama.cpp:server
    volumes:
      - ./models:/models
    command: >
      -m models/Meta-Llama-3.1-8B-Instruct-F16-Q5_K_M.gguf
      -n 450
      -c 2048
      -t 10
      --host 0.0.0.0
      --port 8080
    ports:
      - "8090:8090"

volumes:
  esdata:
    driver: local
